const POKEMON_LIST_TYPES = {
    GET_POKEMON_LIST_SAGA: "GET_POKEMON_LIST_SAGA",

    GET_POKEMON_LIST: "GET_POKEMON_LIST",
    ADD_POKEMON_TO_LIST: "ADD_POKEMON_TO_LIST",
    SET_POKEMON_COUNT: "SET_POKEMON_COUNT",
};

export default POKEMON_LIST_TYPES;
